baseURL = 'https://marie-fourier.github.io'
languageCode = 'en-us'
title = 'My blog'
theme = 'archie'
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate=5 # articles per page

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "A minimal hugo theme focus on content"
  author = 'Marie Fourier'
  mode="light" # color-mode → light,dark,toggle or auto
  useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
  subtitle = ""
  mathjax = true # enable MathJax support
  katex = true # enable KaTeX support

  [params.comments]
    githubRepo = 'marie-fourier/marie-fourier.github.io'
    theme = 'github-light'

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/marie-fourier"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/HubZein"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4